### ISSUE TITLE
Where is use command "/setpublickey"? 

### ISSUE THREAD

**Issue by mentos1** [mfiyalka/telegram-passport#1]
Hi, I realised my private key and public key. I don't understand where I must write the "/setpublickey" command. 

In the section documentation, I can't find the command.
https://core.telegram.org/bots#botfather-commands
 
Can you explain to me? Where must I write "/setpublickey" command?

**Comment by mfiyalka** [comment]
Hello!

You need to send this command to bot BotFather
[https://preview.ibb.co/dvRWUe/2018_09_06_13_28_05.png](url)

**Comment by mentos1** [comment]
Thanks, it worked.
